#!/bin/bash                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                           
for A in $(cat $1);                                                                                                                                                                                                                                                                                                        
do                                                                                                                                                                                                                                                                                                                         
        for B in $(cat $2);                                                                                                                                                                                                                                                                                                
        do                                                                                                                                                                                                                                                                                                                 
                echo $A$B;                                                                                                                                                                                                                                                                                                 
        done;                                                                                                                                                                                                                                                                                                              
done; 
